### PR TITLE
Limit and offset handled in the database

### PR DESCRIPTION
**Pull request by brummett**
This branch adds support for running -limit/-offset queries in the database if the data source supports it.

The SQL will include limit/offset only if there are no changed objects matching the BoolExpr, otherwise the Context will handle it.

### CODE REVIEW

**Comment by ebelter** [comment]
+1 Lots to review here, tried to understand it. Good test coverage.

**Comment by sakoht** [comment]
This is such a tough problem.  Exciting to see you guys tackle it.  I stopped on this ages ago when I got stuck on a hard case of unsaved update/insert/delete putting objects in a different order than in the db.

I skimmed the code but wasn't sure if it hit this hard corner case:

Example:

You grab a model and rename it, but don't save.

You get 100 models, sorted by name, and ask for an offset of 50, limit of 10 (the 6th page).  The model you changed was previously the 45th, and still is in the db, but is now the 85th given its new name, if done in memory.  The results should shift by one.

Given that most ORMs just tolerate leakiness when the db is not in sync with memory, it's probably not a big deal.  But if you fixed it I'd love to see the fix.

**Comment by brummett** [comment]
I believe that case is handled in the test:
https://github.com/genome/UR/pull/85/files/#diff-0b29880e3f1142de6276a4c8a2178820R170

Basically, it's super conservative when deciding to put limit/offset in the SQL.  If the rule matches any changed objects, then it falls back to the old behavior of omitting limit/offset from the SQL and handling limit/offset in the Context.

**Comment by sakoht** [comment]
That's really sweet.  So read-only apps looking at a lot of data get the performance boost, but you never risk getting a wrong answer if changes are happening.

Nice.

**Pull request merged**
