### PR TITLE
Regular expression that matches more quickly on large Data::Dumper dumps.

### PR DESCRIPTION
**Pull request by tmooney**
Our "Model Summary" command has been failing for awhile trying to reprocess invalid workflows.  It ends up taking a very long time to complete, because this regular expression is very slow to match over the dump of an `Workflow::Model` object.  This tweak makes it run much more quickly.

### CODE REVIEW

**Comment by acoffman** [comment]
+1

**Comment by brummett** [comment]
+1

I see the comment about the last 15 lines is wrong

**Comment by tmooney** [comment]
Comment updated.

**Comment by nnutter** [comment]
To educate me could you explain how this helps?

**Comment by tmooney** [comment]
With `/.*\n?/` every substring of each line matches that portion of the regular expression (and any partition of each line into three segments matches `/(?:.*\n?){3}/`).  They're logically equivalent, but Perl's implementation is able to find the proper matches more quickly with the hint that each match ends in either `\n` or the end of the string.  (I tried it on 5.10 and 5.18.)

**Comment by nnutter** [comment]
Thanks. =)

**Pull request merged**
