### PR TITLE
Sort the Default datasource last instead of first.

### PR DESCRIPTION
**Pull request by tmooney**

### CODE REVIEW

**Comment by brummett** [comment]
Ugh... maybe add a test since I already messed this up once
:100:

**Comment by tmooney** [comment]
I added a test for the ordering returned from `_order_data_sources_for_saving()`.  (Is there a better place for this test than a new file?)

**Comment by brummett** [comment]
+1 after tests pass

**Comment by dufeiyu** [comment]
+1 once tests pass

**Comment by tmooney** [comment]
Only one test didn't complete before the most recent run timed out, `Music-6.t`.  It looks like it passes locally:
```
$ apipe-tester genome-prove -I /gscuser/tmooney/git/UR/lib /gscuser/tmooney/git/genome/lib/perl/Genome/Model/Tools/Music.t/Music-6.t 
Running 'genome-prove -I /gscuser/tmooney/git/UR/lib /gscuser/tmooney/git/genome/lib/perl/Genome/Model/Tools/Music.t/Music-6.t' as apipe-tester...
/gscuser/tmooney/git/genome/lib/perl/Genome/Model/Tools/Music.t/Music-6.t .. ok     
All tests successful.
Files=1, Tests=10, 614 wallclock secs ( 0.02 usr  0.01 sys + 611.11 cusr  1.55 csys = 612.69 CPU)                                                                                                                                                                
Result: PASS
```

**Pull request merged**
