### PR TITLE
Command Tree File Globbing

### PR DESCRIPTION
**Pull request by ebelter**
close the quotemeta (\Q..\E) with "\E" before the star
the star is now being escaped in at least v5.26

### CODE REVIEW

**Comment by brummett** [comment]
Looks like this was introduced in #145.  Is it reasonable to write a testcase that would have exposed this?

I looked over the commit that introduced the bug.  There were several similar changes, and it looks like this was the only bad one.

**Comment by ebelter** [comment]
I pushed a test showing the fix returns the correct sub command mapping, and then the current code returns an undef mapping.

**Comment by ebelter** [comment]
Any chance this could get reviewed and merged in?

**Comment by brummett** [comment]
I guess the test I was looking for is not exactly this test... I was looking for a simpler test that would clearly fail when run on the broken version of the code (without your fix to lib/Command/Tree.pm) and succeed with the fix.  This test does some funky monkey-patching to ensure it continues to do the wrong thing even when run on a branch containing the fix.

Also, your test uses File::Slurp which isn't getting installed when the tests are run on TravisCI.  It should either include File::Slurp as a test prerequisite, or be rewritten to not use File::Slurp.

**Comment by ebelter** [comment]
Unfortunately, I don't have to rework the test. I can fix the File::Slurp issue, but if that is not going to be good enough, we can close this PR.

**Comment by brummett** [comment]
I guess just get rid the the test, then.  The fix is obviously correct, I was just trying to avoid similar problems in the future by increasing the test coverage.

**Pull request closed without merging**
