### PR TITLE
shouldn't be telling user to see --help if execute fails

### PR DESCRIPTION
**Pull request by nnutter**

### CODE REVIEW

**Comment by brummett** [comment]
Is there a particular use-case that prompted this?  execute() can return false for any reason, and could be mentioned in the help.

**Comment by nnutter** [comment]
```
$ cat demo.pl 
package Demo::Command;
use strict; use warnings; use UR;
class Demo::Command { is => 'Command::V2' };
sub execute { print "executing\n"; return 0; }
package main;
Demo::Command->execute_with_shell_params_and_exit();
```

```
$ genome-perl demo.pl 
executing
ERROR: Please see 'demo.pl --help' for more information.
```

**Comment by nnutter** [comment]
CI, test this.

**Comment by nnutter** [comment]
I redid the original change as b85413b72dea069b97fb71819e43901380834691.  I also decided that part of the problem was Command::V1 and V2 diverging for, probably, unintended reasons so I tried to reduce the duplication a bit.

**Comment by brummett** [comment]
Seems like a code smell to have ```Command::V1::execute()``` possibly operating on Command::V2 instances.  What about extracting those delegated methods to a common parent class?

**Comment by nnutter** [comment]
For the `genome-integration` failures I've made genome/genome#715.

**Comment by nnutter** [comment]
> Seems like a code smell to have `Command::V1::execute()` possibly operating on `Command::V2` instances. What about extracting those delegated methods to a common parent class?

I'm not sure I agree.  We should discuss it on Monday or something.

**Comment by nnutter** [comment]
CI, test this.

**Comment by nnutter** [comment]
I've pushed a commit to extract common `V1`/`V2` code into `Command::Common`.

**Comment by brummett** [comment]
+1

**Pull request merged**
