### PR TITLE
UR::Context::Transaction is getting original object due to an `unload` change

### PR DESCRIPTION
**Pull request by nnutter**
The recently changed code in `UR::Context::Transaction` is getting all changed
objects incorrectly.  In the case of an `unload` it is re-getting the original
object instead of the deleted object.

### CODE REVIEW

**Comment by nnutter** [comment]
I believe this is just failing because `master` is broken, see genome/UR#81.

**Comment by nnutter** [comment]
CI, test this.

**Comment by brummett** [comment]
When I run the provided test on current master, it runs successfully.  What's supposed to happen?

**Comment by nnutter** [comment]
It failed, as expected, on Travis CI.  For example, [63250496](https://travis-ci.org/genome/UR/jobs/63250496#L470).

**Comment by brummett** [comment]
Got the test to fail for me.
The change looks good
+1

**Comment by ebelter** [comment]
+1

**Pull request merged**
